export const mx = {
    CREATE_MX_RECORD: "CREATE_MX_RECORD",
    CREATE_MX_SPINNER: "CREATE_MX_SPINNER",
    GET_MX_SPINNER: "GET_MX_SPINNER",
    SET_MX_RECORDS: "SET_MX_RECORDS"
}

export const txt = {
    CREATE_TXT_RECORD: "CREATE_TXT_RECORD",
    CREATE_TXT_SPINNER: "CREATE_TXT_SPINNER",
    GET_TXT_SPINNER: "GET_TXT_SPINNER",
    SET_TXT_RECORDS: "SET_TXT_RECORDS"
}
