export const host = {
    CREATE_HOST_RECORD: "CREATE_HOST_RECORD",
    CREATE_HOST_SPINNER: "CREATE_HOST_SPINNER",
    GET_HOST_SPINNER: "GET_HOST_SPINNER",
    SET_HOST_RECORDS: "SET_HOST_RECORDS",
    SET_HOST_RESPONSE_RECORDS: "SET_HOST_RESPONSE_RECORDS",
}
